SELECT LOCATION , DATE, total_cases,total_deaths , (total_deaths/total_cases)*100 AS PCNTGDEATH
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
ORDER BY 1,2

--TOTALL CASE AND TOTAL DEATH
SELECT SUM (total_cases) AS TOTALCASE, SUM(total_deaths) AS TOTALDEATH
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
ORDER BY 1,2  DESC

---TOTAL_CASE_PERCOUNTRY--
SELECT  location, SUM(total_cases) AS TOTAL_CASE_PERCOUNTRY, SUM( total_deaths) AS TOTAL_DEATH_PERCOUNTRY
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
GROUP BY location
ORDER BY 1,2

--CASES OVER TIME --
SELECT  DATE, SUM(new_cases) AS DAILY_CASES
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
GROUP BY  date
ORDER BY DATE


   --TOTAL DEATH ON EVERY CONTINENT---
SELECT  continent , SUM(total_deaths) AS TOTAL_DEATH_CONTINENT
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
GROUP BY   continent
ORDER BY continent DESC


--COUNTRIES WITH THE MOST RATING DEATH---
SELECT location , SUM(total_deaths)*100 / SUM(total_cases ) AS MORALITY_RATE
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
GROUP BY location
ORDER BY MORALITY_RATE DESC

--CONTINENT-- 
SELECT continent, SUM(total_deaths)/SUM(total_cases)*100 AS MOTALITY_RATE_PER_COUNTRY
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
GROUP BY continent
ORDER BY continent DESC


-- COUNTRIES WITH LEAST DEATH--
SELECT location, SUM(total_deaths) AS TOTAL_DEATH_PERCOUNTRY
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
GROUP BY location, total_deaths
HAVING SUM(total_deaths) <=100
ORDER BY location

SELECT location ,SUM( total_deaths) AS MOTARLITY_RATE
FROM [COVID -DEATH]
WHERE continent IS NOT NULL
GROUP BY location
HAVING SUM(total_deaths ) <=110
ORDER BY location

--DAILY CASSES IN THE WORLD---
 SELECT date , SUM (NEW_CASES) AS DAILY_CASES
 FROM [COVID -DEATH]
 WHERE continent IS NOT NULL
 GROUP BY DATE  
 ORDER BY DATE

 ---AVERAGE DAILY CASSES IN THE WORLD--
 SELECT  AVG(DAILY_CASES) AS AVG_DAILY_CASES
 FROM 
 (SELECT date , SUM (NEW_CASES) AS DAILY_CASES
 FROM [COVID -DEATH]
 WHERE continent IS NOT NULL
 GROUP BY DATE  

 ) daily_data;